export enum PERMISSIONS {
  CREATE_COMPANY = "CREATE_COMPANY",
  UPDATE_COMPANY = "UPDATE_COMPANY",
  UPDATE_COMPANY_LOGO = "UPDATE_COMPANY_LOGO",
  VIEW_COMPANY = "VIEW_COMPANY",
  VIEW_USERS = "VIEW_USERS",
  COMPARE_COMPANIES = "COMPARE_COMPANIES",
}
